pretrained_model_name_or_path: 'ckpts'
pretrained_unet_path: 'ckpts'
pretrained_controlnet_path: 'ckpts/controlnet'
revision: null
validation_dataset:
  root_dir: 'exp_debugg'
  num_views: 6
  bg_color: 'black'
  img_wh: [256, 256]
  object_list: 'data_lists/obj_list.json'
  invalid_list: 'data_lists/lvis_invalid_uids_nineviews.json'
  validation: true
  num_validation_samples: 1

save_dir: 'debug_results'

seed: 42
validation_batch_size: 1
dataloader_num_workers: 8

validation_guidance_scales: [1.0]
pipe_validation_kwargs:
  eta: 1.0

pipe_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  num_views: 6

unet_from_pretrained_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  projection_class_embeddings_input_dim: 10  # modify
  num_views: 6
  sample_size: 32
  zero_init_conv_in: false
  zero_init_camera_projection: false
  cd_attention_last: false
  cd_attention_mid: true
  multiview_attention: true
  sparse_mv_attention: false
  mvcd_attention: false
