exp:
    save_dir: 'exp_mvp_cube2cube'
    num_iters: 1000

data:
    mesh_path: 'data/cube.ply'
    mesh_scale: 1.0
    num_subdiv: 3
    gt_from: 'gt_data/cube2cube_detail'

optim:
    adam_lr: 1e-2
    largesteps_lr: 1e-3
    lambda_: 10

renderer:
    resolution: 512

controlnet:
    from_depth: True
    from_normal: False
    pred_depth: True
    pred_normal: True
    num_samples: 1
    resolution: 512
    ddim_steps: 20
    guess_mode: False
    strength: 1.0
    scale: 9.0
    eta: 1.0
    seed: 12345
    prompt: 'A cube with brick detail'
    a_prompt: 'Best quality'
    n_prompt: 'low-res, worse quality, cropped'
