pretrained_model_name_or_path: 'lambdalabs/sd-image-variations-diffusers'
# modify the unet path; use the stage 1 checkpoint
pretrained_unet_path: 'ckpts'
revision: null
train_dataset:
  root_dir: '/scratch/hdd001/home/ycchen/datasets/objaverse_renders'
  object_list: 'data_lists/lvis_uids_filter_by_vertex.json'
  invalid_list: 'data_lists/lvis_invalid_uids_nineviews.json'
  num_views: 6
  bg_color: 'three_choices'
  img_wh: [256, 256]
  validation: false
  num_validation_samples: 32
validation_dataset:
  root_dir: '/scratch/hdd001/home/ycchen/datasets/objaverse_renders'
  object_list: 'data_lists/lvis_uids_filter_by_vertex.json'
  invalid_list: 'data_lists/lvis_invalid_uids_nineviews.json'
  num_views: 6
  bg_color: 'black'
  img_wh: [256, 256]
  validation: true
  num_validation_samples: 32

output_dir: '/scratch/hdd001/home/ycchen/mvcontrolnet/outputs'
vis_dir: 'vis'
logging_dir: 'logs'
seed: 42
train_batch_size: 24 # original paper uses 32
validation_batch_size: 8
max_train_steps: 20000
gradient_accumulation_steps: 2
gradient_checkpointing: true
learning_rate: 5.e-5
lr_scheduler: 'constant_with_warmup'
lr_warmup_steps: 100
snr_gamma: 5.0
use_ema: true 
dataloader_num_workers: 8
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1.e-2
adam_epsilon: 1.e-08
max_grad_norm: 1.0
prediction_type: null
mixed_precision: 'fp16'
report_to: 'wandb'
local_rank: -1
#checkpointing_steps: 5000
checkpointing_steps: 2000
last_global_step: 5000

resume_from_checkpoint: latest
enable_xformers_memory_efficient_attention: true
validation_steps: 100
validation_sanity_check: true
tracker_project_name: 'train_mvwonder3d'

exp_name: 'mvwonder3d'
wandb_dir: '/scratch/hdd001/home/ycchen/mvcontrolnet/wandb'

trainable_modules: ['joint_mid']
use_classifier_free_guidance: true
condition_drop_rate: 0.05
camera_embedding_lr_mult: 10.
scale_input_latents: true

pipe_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  num_views: 6

validation_guidance_scales: [3.]
pipe_validation_kwargs:
  eta: 1.0

unet_from_pretrained_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  projection_class_embeddings_input_dim: 10  # modify
  num_views: 6
  sample_size: 32
  zero_init_conv_in: false
  zero_init_camera_projection: false
  cd_attention_last: false
  cd_attention_mid: true
  multiview_attention: true
  sparse_mv_attention: false
  mvcd_attention: false

num_views: 6
